import type { Metadata } from "next";
import "@/app/globals.css";
import { cn } from "@/lib/utils";

import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased", font.className)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex items-center justify-center">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
